### ISSUE TITLE
Error: Unable to load class 'org.gradle.internal.reflect.Instantiator'.

### ISSUE THREAD

**Issue by vin-blip** [Free-Software-for-Android/Standalone-Calendar#11]
When I imported this git into Android Studio latest version, it downloaded many files from maven repo for like half-an-hour then showed me this error. I can't get around it. I restarted my pc, android studio, re-imported the project; nothing made a difference. Please see the screenshot.
![error](https://cloud.githubusercontent.com/assets/10230911/5629433/5c66257c-95d9-11e4-93c2-8653f11dca81.jpg)

**Comment by dschuermann** [comment]
This will not work in Android Studio. I only created gradle files without any usage of an IDE.
