### ISSUE TITLE
How to do backup

### ISSUE THREAD

**Issue by cljoly** [Free-Software-for-Android/Standalone-Calendar#12]
I couldn't find anywhere how to access to data stored in the calendar.

I would like to copy a file (on a computer, USB key, ...) with my events to back them up.
I prefer do not to use online services.

Is there a solution to do backup this way?

**Comment by ghost** [comment]
You can use another app called "Calendar Import-Export" for this. Another option would be to use cal caldav server.

**Comment by cljoly** [comment]
It works great with [Calendar Import-Export](https://f-droid.org/repository/browse/?fdfilter=Calendar+Import-Export&fdid=org.sufficientlysecure.ical), thanks!
