### ISSUE TITLE
Importing Source Code in Eclipse IDE

### ISSUE THREAD

**Issue by aminalzanki** [Free-Software-for-Android/Standalone-Calendar#6]
Hi,

May I ask, why there have an error while importing in eclipse? Is there any way / configuration I missed? 

Best Regards,

**Comment by dschuermann** [comment]
I never tried importing it in Eclipse.
I created the gradle build files and made some modifications without an IDE to get it compile.

**Comment by aminalzanki** [comment]
Thanks for quick response. By the way, could you please share with me the steps to build it in brief?

**Comment by dschuermann** [comment]
Look in the README ;)
